import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {MeshoptDecoder} from './vendor/addons/libs/meshopt_decoder.module.js';
const view=document.querySelector('#view'),status=document.querySelector('#status'),select=document.querySelector('#item'),download=document.querySelector('#download');
const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;view.append(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(35,1,.001,10000),controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;
scene.add(new T.HemisphereLight(0xffffff,0x98a5a2,2));const light=new T.DirectionalLight(0xffffff,2);light.position.set(3,5,4);scene.add(light);
const draco=new DRACOLoader().setDecoderPath('./vendor/addons/libs/draco/gltf/'),loader=new GLTFLoader().setDRACOLoader(draco).setMeshoptDecoder(MeshoptDecoder);
const items=await(await fetch('./items.json')).json();items.forEach((x,i)=>select.add(new Option(x.name,i)));let active,serial=0;
async function show(){const id=++serial,item=items[select.value||0];status.textContent='Loading…';try{const gltf=await loader.loadAsync(item.file);if(id!==serial)return;if(active){scene.remove(active);active.traverse(o=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m?.dispose()})}active=gltf.scene;scene.add(active);active.updateMatrixWorld(true);const box=new T.Box3().setFromObject(active,true),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()),span=Math.max(size.x,size.y,size.z,.01);camera.near=span/1000;camera.far=span*100;camera.updateProjectionMatrix();camera.position.copy(center).add(new T.Vector3(span*.8,span*.35,span*2.5));controls.target.copy(center);controls.minDistance=span*.4;controls.maxDistance=span*6;controls.update();download.href=item.file;status.textContent='Ready · '+(Number(select.value)+1)+' / '+items.length;window.__itemPreview={ready:true,root:active,name:item.name};}catch(e){status.textContent='Could not load. Please choose the item again.';console.error(e)}}
new ResizeObserver(()=>{renderer.setSize(view.clientWidth,view.clientHeight);camera.aspect=view.clientWidth/view.clientHeight;camera.updateProjectionMatrix()}).observe(view);select.onchange=show;renderer.setAnimationLoop(()=>{if(!document.hidden)renderer.render(scene,camera)});await show();
